chore(deps): Update `jest` to 28.1.0
Following the update of `@types/jest`, update `jest` to resolve this CI issue:

```log
16:47:04   node_modules/@types/jest/index.d.ts(510,25): error TS1005: ',' expected.
16:47:04   node_modules/@types/jest/index.d.ts(510,46): error TS1109: Expression expected.
```